nelmio_cors:
    defaults:
        allow_origin:
            - 'http://localhost:5173'
            - 'https://architecture-logicielle.onrender.com'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        max_age: 3600
    paths:
        '^/api':
            allow_origin:
                - 'http://localhost:5173'
                - 'https://architecture-logicielle.onrender.com'
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600